// Generated by CoffeeScript 1.3.1
(function() {

  describe('highlight', function() {
    beforeEach(function() {
      return loadFixtures('poe.html');
    });
    return describe('default category', function() {
      return it('puts a border', function() {
        return expect("#highlighters span.facet").toHaveClass('border');
      });
    });
  });

}).call(this);
