require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImgSpansController do

  # This should return the minimal set of attributes required to create a valid
  # ImgSpan. As you add validations to ImgSpan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all img_spans as @img_spans" do
      img_span = ImgSpan.create! valid_attributes
      get :index
      assigns(:img_spans).should eq([img_span])
    end
  end

  describe "GET show" do
    it "assigns the requested img_span as @img_span" do
      img_span = ImgSpan.create! valid_attributes
      get :show, :id => img_span.id
      assigns(:img_span).should eq(img_span)
    end
  end

  describe "GET new" do
    it "assigns a new img_span as @img_span" do
      get :new
      assigns(:img_span).should be_a_new(ImgSpan)
    end
  end

  describe "GET edit" do
    it "assigns the requested img_span as @img_span" do
      img_span = ImgSpan.create! valid_attributes
      get :edit, :id => img_span.id
      assigns(:img_span).should eq(img_span)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImgSpan" do
        expect {
          post :create, :img_span => valid_attributes
        }.to change(ImgSpan, :count).by(1)
      end

      it "assigns a newly created img_span as @img_span" do
        post :create, :img_span => valid_attributes
        assigns(:img_span).should be_a(ImgSpan)
        assigns(:img_span).should be_persisted
      end

      it "redirects to the created img_span" do
        post :create, :img_span => valid_attributes
        response.should redirect_to(ImgSpan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved img_span as @img_span" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImgSpan.any_instance.stub(:save).and_return(false)
        post :create, :img_span => {}
        assigns(:img_span).should be_a_new(ImgSpan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImgSpan.any_instance.stub(:save).and_return(false)
        post :create, :img_span => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested img_span" do
        img_span = ImgSpan.create! valid_attributes
        # Assuming there are no other img_spans in the database, this
        # specifies that the ImgSpan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImgSpan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => img_span.id, :img_span => {'these' => 'params'}
      end

      it "assigns the requested img_span as @img_span" do
        img_span = ImgSpan.create! valid_attributes
        put :update, :id => img_span.id, :img_span => valid_attributes
        assigns(:img_span).should eq(img_span)
      end

      it "redirects to the img_span" do
        img_span = ImgSpan.create! valid_attributes
        put :update, :id => img_span.id, :img_span => valid_attributes
        response.should redirect_to(img_span)
      end
    end

    describe "with invalid params" do
      it "assigns the img_span as @img_span" do
        img_span = ImgSpan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImgSpan.any_instance.stub(:save).and_return(false)
        put :update, :id => img_span.id, :img_span => {}
        assigns(:img_span).should eq(img_span)
      end

      it "re-renders the 'edit' template" do
        img_span = ImgSpan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImgSpan.any_instance.stub(:save).and_return(false)
        put :update, :id => img_span.id, :img_span => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested img_span" do
      img_span = ImgSpan.create! valid_attributes
      expect {
        delete :destroy, :id => img_span.id
      }.to change(ImgSpan, :count).by(-1)
    end

    it "redirects to the img_spans list" do
      img_span = ImgSpan.create! valid_attributes
      delete :destroy, :id => img_span.id
      response.should redirect_to(img_spans_url)
    end
  end

end
