require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TextSpansController do

  # This should return the minimal set of attributes required to create a valid
  # TextSpan. As you add validations to TextSpan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all text_spans as @text_spans" do
      text_span = TextSpan.create! valid_attributes
      get :index
      assigns(:text_spans).should eq([text_span])
    end
  end

  describe "GET show" do
    it "assigns the requested text_span as @text_span" do
      text_span = TextSpan.create! valid_attributes
      get :show, :id => text_span.id
      assigns(:text_span).should eq(text_span)
    end
  end

  describe "GET new" do
    it "assigns a new text_span as @text_span" do
      get :new
      assigns(:text_span).should be_a_new(TextSpan)
    end
  end

  describe "GET edit" do
    it "assigns the requested text_span as @text_span" do
      text_span = TextSpan.create! valid_attributes
      get :edit, :id => text_span.id
      assigns(:text_span).should eq(text_span)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TextSpan" do
        expect {
          post :create, :text_span => valid_attributes
        }.to change(TextSpan, :count).by(1)
      end

      it "assigns a newly created text_span as @text_span" do
        post :create, :text_span => valid_attributes
        assigns(:text_span).should be_a(TextSpan)
        assigns(:text_span).should be_persisted
      end

      it "redirects to the created text_span" do
        post :create, :text_span => valid_attributes
        response.should redirect_to(TextSpan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved text_span as @text_span" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextSpan.any_instance.stub(:save).and_return(false)
        post :create, :text_span => {}
        assigns(:text_span).should be_a_new(TextSpan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextSpan.any_instance.stub(:save).and_return(false)
        post :create, :text_span => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested text_span" do
        text_span = TextSpan.create! valid_attributes
        # Assuming there are no other text_spans in the database, this
        # specifies that the TextSpan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TextSpan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => text_span.id, :text_span => {'these' => 'params'}
      end

      it "assigns the requested text_span as @text_span" do
        text_span = TextSpan.create! valid_attributes
        put :update, :id => text_span.id, :text_span => valid_attributes
        assigns(:text_span).should eq(text_span)
      end

      it "redirects to the text_span" do
        text_span = TextSpan.create! valid_attributes
        put :update, :id => text_span.id, :text_span => valid_attributes
        response.should redirect_to(text_span)
      end
    end

    describe "with invalid params" do
      it "assigns the text_span as @text_span" do
        text_span = TextSpan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextSpan.any_instance.stub(:save).and_return(false)
        put :update, :id => text_span.id, :text_span => {}
        assigns(:text_span).should eq(text_span)
      end

      it "re-renders the 'edit' template" do
        text_span = TextSpan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextSpan.any_instance.stub(:save).and_return(false)
        put :update, :id => text_span.id, :text_span => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested text_span" do
      text_span = TextSpan.create! valid_attributes
      expect {
        delete :destroy, :id => text_span.id
      }.to change(TextSpan, :count).by(-1)
    end

    it "redirects to the text_spans list" do
      text_span = TextSpan.create! valid_attributes
      delete :destroy, :id => text_span.id
      response.should redirect_to(text_spans_url)
    end
  end

end
