require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TextDocsController do

  # This should return the minimal set of attributes required to create a valid
  # TextDoc. As you add validations to TextDoc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all text_docs as @text_docs" do
      text_doc = TextDoc.create! valid_attributes
      get :index
      assigns(:text_docs).should eq([text_doc])
    end
  end

  describe "GET show" do
    it "assigns the requested text_doc as @text_doc" do
      text_doc = TextDoc.create! valid_attributes
      get :show, :id => text_doc.id
      assigns(:text_doc).should eq(text_doc)
    end
  end

  describe "GET new" do
    it "assigns a new text_doc as @text_doc" do
      get :new
      assigns(:text_doc).should be_a_new(TextDoc)
    end
  end

  describe "GET edit" do
    it "assigns the requested text_doc as @text_doc" do
      text_doc = TextDoc.create! valid_attributes
      get :edit, :id => text_doc.id
      assigns(:text_doc).should eq(text_doc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TextDoc" do
        expect {
          post :create, :text_doc => valid_attributes
        }.to change(TextDoc, :count).by(1)
      end

      it "assigns a newly created text_doc as @text_doc" do
        post :create, :text_doc => valid_attributes
        assigns(:text_doc).should be_a(TextDoc)
        assigns(:text_doc).should be_persisted
      end

      it "redirects to the created text_doc" do
        post :create, :text_doc => valid_attributes
        response.should redirect_to(TextDoc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved text_doc as @text_doc" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextDoc.any_instance.stub(:save).and_return(false)
        post :create, :text_doc => {}
        assigns(:text_doc).should be_a_new(TextDoc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextDoc.any_instance.stub(:save).and_return(false)
        post :create, :text_doc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested text_doc" do
        text_doc = TextDoc.create! valid_attributes
        # Assuming there are no other text_docs in the database, this
        # specifies that the TextDoc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TextDoc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => text_doc.id, :text_doc => {'these' => 'params'}
      end

      it "assigns the requested text_doc as @text_doc" do
        text_doc = TextDoc.create! valid_attributes
        put :update, :id => text_doc.id, :text_doc => valid_attributes
        assigns(:text_doc).should eq(text_doc)
      end

      it "redirects to the text_doc" do
        text_doc = TextDoc.create! valid_attributes
        put :update, :id => text_doc.id, :text_doc => valid_attributes
        response.should redirect_to(text_doc)
      end
    end

    describe "with invalid params" do
      it "assigns the text_doc as @text_doc" do
        text_doc = TextDoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextDoc.any_instance.stub(:save).and_return(false)
        put :update, :id => text_doc.id, :text_doc => {}
        assigns(:text_doc).should eq(text_doc)
      end

      it "re-renders the 'edit' template" do
        text_doc = TextDoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextDoc.any_instance.stub(:save).and_return(false)
        put :update, :id => text_doc.id, :text_doc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested text_doc" do
      text_doc = TextDoc.create! valid_attributes
      expect {
        delete :destroy, :id => text_doc.id
      }.to change(TextDoc, :count).by(-1)
    end

    it "redirects to the text_docs list" do
      text_doc = TextDoc.create! valid_attributes
      delete :destroy, :id => text_doc.id
      response.should redirect_to(text_docs_url)
    end
  end

end
